server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
          id: core-ai-route
          uri: http://localhost:8081 # Points to Core AI Service
          predicates:
            - Path=/api/v1/ai/** # Intercepts these requests

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always